[docs] Sequenzsiagramme überarbieten
weichware10/dokumente pull request #26
Opened 2022-01-29 14:50 UTC by Rotwolf

Analyse ist schon geyeetet.
Sequendiagramm Eyetracking soll so beiben !?

- [ ] Codecharts
- [ ] Zoommaps

2022-01-29 17:18 UTC, joshuajeschek commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +cc -> c : getTrailData()
Mal davon abgesehen, dass ihr euch hier verschrieben habt, der Aufruf an ConfigClient ist nicht `getTrialData()` sondern viel mehr `getConfig()`
und dann könnte da vielleicht noch ein Kommentar hin: "auslesen und verarbeiten der Konfiguration"

2022-01-29 17:21 UTC, joshuajeschek commented
vielleicht wäre es auch noch ganz praktisch bei den ganzen Initialisierungen bei den Konstrukutoren ein "new" davorzusetzen, damit klar ist was damit gemeint ist :)

2022-01-29 17:23 UTC, joshuajeschek commented
sowohl bei ZoomMaps als auch bei CodeCharts wird im Constructor ein neues TrialData Objekt erstellt.
Das könnte sich auch noch gut tun das mit reinzuschreiben, und dann auch im eigentlichen Versuchen einen Verweis zu machen dass das da reingeschrieben wird

2022-01-29 17:31 UTC, joshuajeschek commented
auch der Aufruf von `getData()` existiert so im Code nicht, da wäre es ganz praktiscch wenn ihr euch einfach den Code daneben legt und da mal schaut, was wirklich passiert! man könnte aber zum Beispiel das folgende:
```java
imageUrl = configClient.getConfig().getImageUrl();
question = configClient.getConfig().getQuestion();
```
(aus ZoomCalculator Konstruktor)

im Diagramm zu:
```getConfig()```

vereinfachen ^^

2022-01-30 09:52 UTC, joshuajeschek requested changes
* code beachten
* TrialData hinzufügen

2022-01-31 16:01 UTC, Rotwolf commented
So in Ordnung?

2022-01-31 21:21 UTC, TheDarkDesync commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +note left : auslesen und verarbieten der Konfiguration
```suggestion
note left : Auslesen und Verarbeiten der Konfiguration
```

2022-01-31 21:21 UTC, TheDarkDesync commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +        cc -> cp : Anpassen von Raster
```suggestion
        cc -> cp : Anpassen vom Raster
```

2022-01-31 21:22 UTC, joshuajeschek commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +note left : auslesen und verarbieten der Konfiguration
wenn du genau aufgepasst hättest wäre dir aufgefallen dass die dort gar nix bringt die notiz

2022-01-31 21:23 UTC, TheDarkDesync commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +participant CodeChartsController    as ct
```suggestion

```

2022-01-31 21:31 UTC, TheDarkDesync commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +    ci --> co : Data
```suggestion
    ci --> co : Data
    opt "Data != null"
        co -> td : trialData.addDataPoint(viewport, depth)
    end
```

2022-01-31 21:39 UTC, TheDarkDesync commented on uml-sequence/zoommaps/sequenz-zoommaps.puml
> +note left : new TrialData
```suggestion
note left: TrialData Objekt zum Abspeichern der Ergebnisse
```
einheitlich, da es bei CodeCharts so ist

2022-01-31 21:41 UTC, TheDarkDesync commented on uml-sequence/zoommaps/sequenz-zoommaps.puml
> +deactivate zi
```suggestion
== Ende ==
deactivate zb
deactivate zi
deactivate zc
g -> zm : endTest(String answer)
td --> zm : erhobene Daten
deactivate td
```
Sieht besser auch. Wenn es falsch ist ignorieren

2022-01-31 21:41 UTC, TheDarkDesync commented on uml-sequence/zoommaps/sequenz-zoommaps.puml
> +    zc -> zb : getImageCoordinbates(raw)
```suggestion
    zc -> zb : getImageCoordinates(raw)
```

2022-02-01 07:16 UTC, Rotwolf commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +note left : auslesen und verarbieten der Konfiguration
Wo muss es denn hin?
Oder soll es raus?

2022-02-01 07:18 UTC, Rotwolf commented on uml-sequence/zoommaps/sequenz-zoommaps.puml
> +deactivate zi
Ich bin mir unschlüssig würde es aber so lassen!?

2022-02-01 08:49 UTC, joshuajeschek commented on uml-sequence/zoommaps/sequenz-zoommaps.puml
> +deactivate zi
Ist besser so wie vorgeschlagen ^^

2022-02-01 09:43 UTC, joshuajeschek commented on uml-sequence/codecharts/sequenz-codecharts.puml
> +note left : auslesen und verarbieten der Konfiguration
raus, weil der Pfeil der zurückgeht hat ja schon "Konfiguration" oder so dran stehen

2022-02-01 09:44 UTC, joshuajeschek approved these changes

2022-02-01 11:52 UTC, TheDarkDesync approved these changes
jetzt passt alles

2022-02-01 16:46 UTC, merged